parameters:
    dt.oauth.user_provider.class: Dt\OAuthBundle\Security\Core\User\DtFOSUBUserProvider
    #dt.oauth.user.provider.entity.class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider

services:
    #hwi_oauth.user.provider.entity:
        #class: %dt.oauth.user.provider.entity.class%
    dt.oauth.user_provider:
        class: %dt.oauth.user_provider.class%
        arguments: ['@fos_user.user_manager', { facebook: facebook_id }]
