aboutusersreply_index:
    path:     /
    defaults: { _controller: "DtUserBundle:AboutUsersReply:index" }
    methods:  GET

aboutusersreply_show:
    path:     /{id}/show
    defaults: { _controller: "DtUserBundle:AboutUsersReply:show" }
    methods:  GET

aboutusersreply_new:
    path:     /new
    defaults: { _controller: "DtUserBundle:AboutUsersReply:new" }
    methods:  [GET, POST]

aboutusersreply_edit:
    path:     /{id}/edit
    defaults: { _controller: "DtUserBundle:AboutUsersReply:edit" }
    methods:  [GET, POST]

aboutusersreply_delete:
    path:     /{id}/delete
    defaults: { _controller: "DtUserBundle:AboutUsersReply:delete" }
    methods:  DELETE
