dt_user_user_picture_index:
    path:     /
    defaults: { _controller: "DtUserBundle:UserPicture:index" }
    methods:  GET

#dt_user_user_picture_show:
#    path:     /{id}/show
#    defaults: { _controller: "DtUserBundle:UserPicture:show" }
#    methods:  GET

dt_user_user_picture_new:
    path:     /new
    defaults: { _controller: "DtUserBundle:UserPicture:new" }
    methods:  [GET, POST]

dt_user_user_picture_edit:
    path:     /{pictureId}/edit
    defaults: { _controller: "DtUserBundle:UserPicture:edit" }
    methods:  [GET, POST]
   
dt_user_user_picture_update_user_profile_picture:
    path:     /{pictureId}/update-user-profile-picture
    defaults: { _controller: "DtUserBundle:UserPicture:updateUserProfilePicture" }
    methods:  [GET, POST]    

dt_user_user_picture_delete:
    path:     /{pictureId}/delete
    defaults: { _controller: "DtUserBundle:UserPicture:delete" }
    methods:  DELETE
