#dt_user_about_users_reply:
#    resource: "@DtUserBundle/Controller/AboutUsersReplyController.php"
#    type:     annotation

dt_admin:
    resource: "@DtAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login/connect

#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google   
    
app:
    resource: '@AppBundle/Resources/config/routing.yml'

dt_o_auth:
    resource: "@DtOAuthBundle/Resources/config/routing.yml"
    prefix:   /

dt_search:
    resource: "@DtSearchBundle/Resources/config/routing.yml"
    prefix:   /

dt_user:
    resource: "@DtUserBundle/Resources/config/routing.yml"
    prefix:   /membres

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /membres

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /membres/profile
            
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"    
    
  

