hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login/connect

#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /login

facebook_login:
    path: /login/check-facebook
    
app:
    resource: '@AppBundle/Resources/config/routing.yml'

dt_o_auth:
    resource: "@DtOAuthBundle/Resources/config/routing.yml"
    prefix:   /

dt_search:
    resource: "@DtSearchBundle/Resources/config/routing.yml"
    prefix:   /

dt_user:
    resource: "@DtUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"    

