dt_admin_homepage:
    path:     /
    defaults: { _controller: DtAdminBundle:Admin:index }

dt_admin_users:
    path: /users
    defaults: { _controller: DtAdminBundle:Users:index }
    
dt_admin_about_user:
    resource: "@DtAdminBundle/Resources/config/routing/aboutuser.yml"
    prefix:   /about-user

dt_admin_aboutusermeta:
        resource: "@DtAdminBundle/Resources/config/routing/aboutusermeta.yml"
        prefix:   /about-user-meta

    

