dt_admin_about-users:
    resource: "@DtAdminBundle/Resources/config/routing/aboutusers.yml"
    prefix:   /about-users

dt_admin_homepage:
    path:     /
    defaults: { _controller: DtAdminBundle:Admin:index }

dt_admin_users:
    path: /users
    defaults: { _controller: DtAdminBundle:Users:index }
    

