dt_user_members:
    path:     /
    defaults: { _controller: DtUserBundle:Members:members }
    
dt_user_members_history:
    path: /{slug}/historique
    defaults: { _controller: DtUserBundle:Members:history }
    
dt_user_members_mon_compte:
    path: /{slug}/mon-compte
    defaults: { _controller: DtUserBundle:Compte:view }
    
###
# Edit dans mon compte - Toutes editions se fait en js 
###
dt_user_edit_profile_moi: 
    path: /{slug}/mon-compte/profile/edit/moi
    defaults: { _controller: DtUserBundle:Compte:editMoi }

dt_user_edit_profile_reseaux_sociaux: 
    path: /{slug}/mon-compte/profile/edit/reseaux-sociaux
    defaults: { _controller: DtUserBundle:Compte:editReseauxSociaux }
    
dt_user_edit_profile_qui_suis_je: 
    path: /{slug}/mon-compte/profile/edit/qui-suis-je
    defaults: { _controller: DtUserBundle:Compte:editQuiSuisJe }    
