dt_user_homepage:
    path:     /members
    defaults: { _controller: DtUserBundle:Members:index }

dt_user_member_history:
    path: history
    defaults: { _controller: DtUserBundle:Members:history }