parameters:
    dt.oauth.user_provider.class: Dt\UserBundle\Security\Core\User\DtFOSUBUserProvider
    dt_user.mailer.twig_swift.class: Dt\UserBundle\Mailer\TwigSwiftMailer
    # Listener
    dt_user.listener.oauth_user.class: Dt\UserBundle\EventListener\LoadUserByOAuthUserListener
    dt_user.listener.redirect.class: Dt\UserBundle\EventListener\RedirectListener
    # Manager Entity
    dt_user.about_user_reply.entity.class: Dt\UserBundle\Entity\AboutUserReply
    dt_user.looking_for.entity.class: Dt\UserBundle\Entity\LookingFor
    # Manager Class
    dt_user.about_user_reply.manager.class: Dt\UserBundle\Doctrine\AboutUserReplyManager
    dt_user.looking_for.manager.class: Dt\UserBundle\Doctrine\LookingForManager
    # Form
    dt_user.about_user_reply.form.type.class: Dt\UserBundle\Form\Type\AboutUserReplyType

services:
    dt.oauth.user_provider:
        class: %dt.oauth.user_provider.class%
        arguments: ['@fos_user.user_manager', { facebook: facebookId, google: googleId }, '@event_dispatcher', '@validator', '@session']

    # Listener
    dt_user.listener.oauth_user:
        class: %dt_user.listener.oauth_user.class%
        arguments: ['@stof_doctrine_extensions.uploadable.manager', '@oneup_acl.manager']
        tags:
            - { name: kernel.event_subscriber }
            
    dt_user.listener.redirect:
        class: %dt_user.listener.redirect.class%
        arguments: ['@security.authorization_checker', '@router']
        tags:
            - { name: kernel.event_subscriber }    
            
    # Manager
    about_user_reply.manager:
        class: '%dt_user.about_user_reply.manager.class%'
        arguments: ["@doctrine.orm.entity_manager", "%dt_user.looking_for.entity.class%"]
    
    looking_for.manager:
        class: '%dt_user.looking_for.manager.class%'
        arguments: ["@doctrine.orm.entity_manager", "%dt_user.looking_for.entity.class%"]    
        
    # Form Type
    dt_user.form.type.about_user_reply_type:
        class: '%dt_user.about_user_reply.form.type.class%'
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@fos_user.user_manager']
        tags:
            - { name: form.type }  
