parameters:
    dt.oauth.user_provider.class: Dt\UserBundle\Security\Core\User\DtFOSUBUserProvider
    dt_user.mailer.twig_swift.class: Dt\UserBundle\Mailer\TwigSwiftMailer

services:
    dt.oauth.user_provider:
        class: %dt.oauth.user_provider.class%
        arguments: ['@fos_user.user_manager', { facebook: facebook_id }]

