parameters:
    app.menu_builder.class: AppBundle\Menu\MenuBuilder
    # Extensions Class
    app.twig.country_extension.class: AppBundle\Twig\Extensions\CountryExtension
    app.twig.file_exists_extension.class: AppBundle\Twig\Extensions\FileExistsExtension
    # Manager Class
    app_bundle.base.manager.class: AppBundle\Doctrine\BaseManager
    
services:
    # Gos WebSocket Bundle
    pdo:
        class: PDO
        arguments:
            dsn: 'mysql:host=%database_host%;dbname=%database_name%'
            user: %database_user%
            password: %database_password%
        calls:
            - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
#        arguments:
#            - 'mysql:host=%database_host%;dbname=%database_name%'
#            - { db_table: sessions, db_username: '%database_user%', db_password: '%database_password%' }
        arguments: [@pdo, {lock_mode: 0}]
    
#    gos_web_scocket.client_storage.driver.predis:
#        class: AppBundle\WebSocket\Client\Driver\PredisDriver
#        arguments:
#            - @snc_redis.cache
#            - %web_socket_server.client_storage.prefix% #(optionally)if you use prefix
            
    gos_web_socket_server.client_event.listener:
        class: AppBundle\EventListener\AppClientEventListener
        tags:
            - { name: kernel.event_listener, event: 'gos_web_socket.client_connected', method: onClientConnect }
            - { name: kernel.event_listener, event: 'gos_web_socket.client_disconnected', method: onClientDisconnect }
            - { name: kernel.event_listener, event: 'gos_web_socket.client_error', method: onClientError }
            - { name: kernel.event_listener, event: 'gos_web_socket.server_launched', method: onServerStart }
            - { name: kernel.event_listener, event: 'gos_web_socket.client_rejected', method: onClientRejected }
            
    # End Gos WebSocket Bundle
        
    app.menu_builder:
        class: '%app.menu_builder.class%'
        arguments: ["@knp_menu.factory", "@security.token_storage", "@request_stack"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createLoginMenu, alias: login }
            - { name: knp_menu.menu_builder, method: createLogoutMenu, alias: logout }
            - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: sidebar }
            
    # Twig Extensions
    app.twig.country_extension:
        class: '%app.twig.country_extension.class%'
        public: false
        tags:
            - { name: twig.extension }
            
    app.twig.file_exists_extension:
        class: '%app.twig.file_exists_extension.class%'
        public: false
        tags:
            - { name: twig.extension }        

    # Manager
    base.manager:
        class: '%app_bundle.base.manager.class%'
        arguments: ["@doctrine.orm.entity_manager"]