parameters:
    app.menu_builder.class: AppBundle\Menu\MenuBuilder
services:
    app.menu_builder:
        class: '%app.menu_builder.class%'
        arguments: ["@knp_menu.factory", "@security.token_storage"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createLoginMenu, alias: login }
            - { name: knp_menu.menu_builder, method: createLogoutMenu, alias: logout }
            - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: sidebar }