<?php

namespace Dt\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AboutUsersReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutUsersReplyRepository extends EntityRepository
{
}
