dt_admin.about_user.index:
    path:     /
    defaults: { _controller: "DtAdminBundle:AboutUser:index" }
    methods:  GET

dt_admin.about_user.show:
    path:     /{id}/show
    defaults: { _controller: "DtAdminBundle:AboutUser:show" }
    methods:  GET

dt_admin.about_user.new:
    path:     /new
    defaults: { _controller: "DtAdminBundle:AboutUser:new" }
    methods:  [GET, POST]

dt_admin.about_user.edit:
    path:     /{id}/edit
    defaults: { _controller: "DtAdminBundle:AboutUser:edit" }
    methods:  [GET, POST]

dt_admin.about_user.delete:
    path:     /{id}/delete
    defaults: { _controller: "DtAdminBundle:AboutUser:delete" }
    methods:  DELETE

      