<?php

namespace Dt\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AboutUserMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutUserMetaRepository extends EntityRepository
{
}
