<?php

namespace Dt\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LookingForMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LookingForMetaRepository extends EntityRepository
{
}
